name: "blog"
mode: "dev"
port: 8080
start_time: "2021-05-15"

log:
  level: "debug"
  filename: "blog_app.log"
  max_size: 200
  max_age: 7
  max_backups: 2

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "Cqupt.2020"
  db_name: "blog"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
